# Generated by Django 6.0.4 on 2026-06-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='vehiculos/')),
                ('placa', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('tipo_combustible', models.CharField(max_length=20)),
                ('seguro_vigente', models.BooleanField()),
                ('anio_modelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf', models.FileField(upload_to='mantenimientos/')),
                ('fecha_servicio', models.DateField()),
                ('costo_taller', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_mantenimiento', models.CharField(max_length=20)),
                ('repuestos_cambiados', models.TextField()),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Flota.vehiculo')),
            ],
        ),
    ]
